# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=14, unique=True)),
                ('quantidade_maxima', models.IntegerField(blank=True, null=True)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[['coapac', 'COAPAC'], ['grafica', 'Grafica'], ['prof', 'Professor']], max_length=7)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descri\xe7\xe3o')),
                ('totalFolhas', models.IntegerField(verbose_name='Quantidade de Laudas')),
                ('totalAlunos', models.IntegerField(verbose_name='Quantidade de Alunos')),
                ('totalGeral', models.IntegerField(blank=True, null=True)),
                ('impresso', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('pendente', models.BooleanField(default=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('professor_message', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o')),
                ('coapac_message', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o')),
                ('grafica_message', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o')),
                ('coapac_message_author', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coapac_message_author', to=settings.AUTH_USER_MODEL)),
                ('grafica_message_author', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafica_message_author', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
