# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('quantidade_maxima', models.IntegerField()),
                ('quantidade_atual', models.IntegerField()),
                ('tipo', models.CharField(max_length=7)),
                ('is_superuser', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalFolhas', models.IntegerField()),
                ('totalAlunos', models.IntegerField()),
                ('totalGeral', models.IntegerField()),
                ('impresso', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('pendente', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
