# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='quantidade_atual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='quantidade_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
