# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[['coapac', 'COAPAC'], ['grafica', 'Grafica'], ['professor', 'Professor']], max_length=7),
        ),
    ]
