# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20190606_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[['coapac', 'COAPAC'], ['grafica', 'Grafica'], ['professor', 'Professor']], default='professor', max_length=7),
        ),
    ]
