# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20160829_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
