# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_solicitacao_data_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='totalAlunos',
            field=models.IntegerField(verbose_name='Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='totalFolhas',
            field=models.IntegerField(verbose_name='Quantidade de Laudas'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='totalGeral',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
