# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_auto_20160829_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
