# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0006_solicitacao_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
