# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0008_auto_20160830_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='descricao',
            field=models.CharField(default='', max_length=200, verbose_name='Descri\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='quantidade_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[['coapac', 'COAPAC'], ['grafica', 'Grafica'], ['prof', 'Professor']], max_length=7),
        ),
    ]
