# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0009_auto_20160830_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='coapac_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='grafica_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='professor_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
    ]
