# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0010_auto_20160831_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='coapac_message',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='grafica_message',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='professor_message',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
    ]
