# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0011_auto_20160831_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='coapac_message_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coapac_message_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='grafica_message_author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='grafica_message_author', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
